<a href="https://colab.research.google.com/github/Jency07/machine-learning/blob/main/Simple_ML_Model_20MAI0026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**BUILDING A SIMPLE ML MODEL**

***Import the libraries***

In [ ]:
import pandas as pd
import numpy as np
import sklearn.datasets

***Load the Cancer dataset available in sklearn***

In [ ]:
cancer_ds = sklearn.datasets.load_breast_cancer()

In [ ]:
#Moving the features and target values into variables x and y
X=cancer_ds.data
Y=cancer_ds.target
print(X)
print(Y)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [ ]:
#Constructing a dataframe to hold the features and target
data = pd.DataFrame(cancer_ds.data, columns = cancer_ds.feature_names)
data['class']= cancer_ds.target

***Exploring the dataset using dataframe methods***

In [ ]:
#To display first n records(n=5 by default)
data.head()

mean radius  mean texture  ...  worst fractal dimension  class
0        17.99         10.38  ...                  0.11890      0
1        20.57         17.77  ...                  0.08902      0
2        19.69         21.25  ...                  0.08758      0
3        11.42         20.38  ...                  0.17300      0
4        20.29         14.34  ...                  0.07678      0

[5 rows x 31 columns]

In [ ]:
#To display last n records(n=5 by default)
data.tail()

mean radius  mean texture  ...  worst fractal dimension  class
564        21.56         22.39  ...                  0.07115      0
565        20.13         28.25  ...                  0.06637      0
566        16.60         28.08  ...                  0.07820      0
567        20.60         29.33  ...                  0.12400      0
568         7.76         24.54  ...                  0.07039      1

[5 rows x 31 columns]

In [ ]:
#To get an insight of the features based on various standard measures
data.describe()

mean radius  mean texture  ...  worst fractal dimension       class
count   569.000000    569.000000  ...               569.000000  569.000000
mean     14.127292     19.289649  ...                 0.083946    0.627417
std       3.524049      4.301036  ...                 0.018061    0.483918
min       6.981000      9.710000  ...                 0.055040    0.000000
25%      11.700000     16.170000  ...                 0.071460    0.000000
50%      13.370000     18.840000  ...                 0.080040    1.000000
75%      15.780000     21.800000  ...                 0.092080    1.000000
max      28.110000     39.280000  ...                 0.207500    1.000000

[8 rows x 31 columns]

In [ ]:
#To know how many malignant and benign values class column has
data['class'].value_counts()

1    357
0    212
Name: class, dtype: int64

In [ ]:
#To know the possible values of the target variable
print(cancer_ds.target_names)

['malignant' 'benign']


In [ ]:
#To group the dataset based on the mean of class column
data.groupby('class').mean()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
class                             ...                                         
0        17.462830     21.604906  ...        0.323468                 0.091530
1        12.146524     17.914762  ...        0.270246                 0.079442

[2 rows x 30 columns]

In [ ]:
#To group the dataset based on the mean of mean area feature
data.groupby('mean area').mean()

mean radius  mean texture  ...  worst fractal dimension  class
mean area                             ...                                
143.5            6.981         13.43  ...                  0.09382    1.0
170.4            7.691         25.44  ...                  0.10660    1.0
178.8            7.729         25.49  ...                  0.09938    1.0
181.0            7.760         24.54  ...                  0.07039    1.0
201.9            8.196         16.84  ...                  0.07409    1.0
...                ...           ...  ...                      ...    ...
1878.0          25.220         24.91  ...                  0.10510    0.0
2010.0          25.730         17.46  ...                  0.08815    0.0
2250.0          27.220         21.87  ...                  0.08082    0.0
2499.0          28.110         18.47  ...                  0.05525    0.0
2501.0          27.420         26.27  ...                  0.07427    0.0

[539 rows x 30 columns]

In [ ]:
#To group the dataset based on the mean of mean radius feature
data.groupby('mean radius').mean()

mean texture  mean perimeter  ...  worst fractal dimension  class
mean radius                                ...                                
6.981               13.43           43.79  ...                  0.09382    1.0
7.691               25.44           48.34  ...                  0.10660    1.0
7.729               25.49           47.98  ...                  0.09938    1.0
7.760               24.54           47.92  ...                  0.07039    1.0
8.196               16.84           51.71  ...                  0.07409    1.0
...                   ...             ...  ...                      ...    ...
25.220              24.91          171.50  ...                  0.10510    0.0
25.730              17.46          174.20  ...                  0.08815    0.0
27.220              21.87          182.10  ...                  0.08082    0.0
27.420              26.27          186.90  ...                  0.07427    0.0
28.110              18.47          188.50  ...                  0.05525    0.0

[456 rows x 30 columns]



---



***Train test split***

The dataset has to split into training data and testing data.Doing it manually is not efficient. We have a train_test_split method from sklearn which simplifies the job for us.

It can split the data based on the ratios we input using test_size parameter.

Stratify parameter ensures the dataset is split in a balanced manner(equal positives and negatives) in both testing and training sets.

Random_state parameter ensures the same set of data is considered for every execution of the model so as to provide reproducible results.

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = data.drop('class',axis=1)
Y = data['class']

*Exploring test_size parameter:*

In [ ]:
#magical line of code to split 
X_train, X_test ,Y_train, Y_test = train_test_split(X,Y,test_size=0.1)

In [ ]:
#Splitting data in 80:20 ratio - test_size=0.2 
X_train, X_test ,Y_train, Y_test = train_test_split(X,Y,test_size=0.2)
print(X.shape,X_train.shape,X_test.shape)
print(Y.shape,Y_train.shape,Y_test.shape)
print(Y.mean(),Y_train.mean(),Y_test.mean())

(569, 30) (455, 30) (114, 30)
(569,) (455,) (114,)
0.6274165202108963 0.6329670329670329 0.6052631578947368


*Exploring stratify parameter:*

Stratify parameter ensures the dataset is split in a balanced manner(equal positives and negatives) in both testing and training sets.

Note the difference in mean values of Y_train,Y_test before and after using stratify.When stratify=Y the mean of train and test tends to be almost same

In [ ]:
#To ensure balnced split of data use stratify=Y
X_train, X_test ,Y_train, Y_test = train_test_split(X,Y,test_size=0.2, stratify = Y)
print(X.shape,X_train.shape,X_test.shape)
print(Y.shape,Y_train.shape,Y_test.shape)
print(Y.mean(),Y_train.mean(),Y_test.mean())

(569, 30) (455, 30) (114, 30)
(569,) (455,) (114,)
0.6274165202108963 0.6263736263736264 0.631578947368421


*Exploring random_state parameter:*

In [ ]:
#Random state parameter ensures reproducible results by controlling the randomness in which data is split in every iteration
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=0)
print(X_train.mean(),X_test.mean(),X.mean())

mean radius                 14.140697
mean texture                19.228791
mean perimeter              92.049341
mean area                  657.659121
mean smoothness              0.096481
mean compactness             0.104119
mean concavity               0.087923
mean concave points          0.049103
mean symmetry                0.181072
mean fractal dimension       0.062719
radius error                 0.404835
texture error                1.214218
perimeter error              2.876167
area error                  40.688165
smoothness error             0.007084
compactness error            0.025323
concavity error              0.031098
concave points error         0.011803
symmetry error               0.020547
fractal dimension error      0.003742
worst radius                16.277292
worst texture               25.591780
worst perimeter            107.365055
worst area                 883.720440
worst smoothness             0.132465
worst compactness            0.254187
worst concav

***Exploring shuffle parameter:***

It tells whether or not to shuffle the data before splitting. If shuffle=False then stratify must be None.
shuffle=True by default

In [ ]:
X_train, X_test ,Y_train, Y_test = train_test_split(X,Y,test_size=0.2, stratify = None,shuffle=True)
print(X_train.mean(), X_test.mean, X.mean())

mean radius                 14.137637
mean texture                19.232286
mean perimeter              92.024374
mean area                  654.656484
mean smoothness              0.096369
mean compactness             0.103684
mean concavity               0.087988
mean concave points          0.048634
mean symmetry                0.181426
mean fractal dimension       0.062763
radius error                 0.402345
texture error                1.205831
perimeter error              2.844385
area error                  39.789552
smoothness error             0.006905
compactness error            0.025014
concavity error              0.031588
concave points error         0.011747
symmetry error               0.020504
fractal dimension error      0.003781
worst radius                16.270822
worst texture               25.603099
worst perimeter            107.293253
worst area                 878.846813
worst smoothness             0.132151
worst compactness            0.252026
worst concav

In [ ]:
#Display the shape of Y,Y_train and Y_test
print(Y.shape,Y_train.shape,Y_test.shape)

(569,) (455,) (114,)


In [ ]:
#Display the shape of X,X_train and X_test
print(X.shape ,X_train.shape,X_test.shape)

(569, 30) (455, 30) (114, 30)


In [ ]:
#Display the mean of Y,Y_train and Y_test
print(Y.mean(), Y_train.mean(),Y_test.mean())

0.6274165202108963 0.6263736263736264 0.631578947368421


In [ ]:
#Display the mean of X,X_train and X_test
print(X_train.mean(), X_test.mean, X.mean())

mean radius                 14.140697
mean texture                19.228791
mean perimeter              92.049341
mean area                  657.659121
mean smoothness              0.096481
mean compactness             0.104119
mean concavity               0.087923
mean concave points          0.049103
mean symmetry                0.181072
mean fractal dimension       0.062719
radius error                 0.404835
texture error                1.214218
perimeter error              2.876167
area error                  40.688165
smoothness error             0.007084
compactness error            0.025323
concavity error              0.031098
concave points error         0.011803
symmetry error               0.020547
fractal dimension error      0.003742
worst radius                16.277292
worst texture               25.591780
worst perimeter            107.365055
worst area                 883.720440
worst smoothness             0.132465
worst compactness            0.254187
worst concav

***Binarization***

The domain of features can be huge.The values can be transformed into a scale of 0 and 1 for ease and to avoid a complex model if the purpose of the model can still be met.

In [ ]:
#binarization of input values
X_binarised_train = X_train.apply(pd.cut , bins=2,labels=[1,0])
X_binarised_test = X_test.apply(pd.cut,bins=2, labels=[1,0])


In [ ]:
#Converting dataframes into numpy array
X_binarised_train = X_binarised_train.values
X_binarised_test = X_binarised_test.values


***Training the model***

In [ ]:
#Simple training model 
 
#Training the model
b_optimal=0
max_accuracy=0
for b in range (X_binarised_train.shape[1]+1):
    accurate_rows =0

    for x,y in zip(X_binarised_train, Y_train):
        #Predicting the target value
        y_pred=(np.sum(x)>=b)
        #Checking if prediction is correct and counting the number of accurate predictions
        accurate_rows +=(y == y_pred )
    #Calculating the accuracy for every value of b
    # Accuracy = Num of rows predicted correctly/total number of rows
    accuracy=(accurate_rows/X_binarised_train.shape[0])*100

    print("b="+str(b),end=" ")
    print("No of Accurate rows= "+str(accurate_rows),end=" ")
    print("Accuracy= "+str(accuracy)+str("%\n"))
      
    #Finding the optimal value of b
    if(accuracy>max_accuracy):
      max_accuracy=accuracy
      b_optimal=b

print("***********************************************")
print("Maximum Training Accuracy= "+str(max_accuracy)+str("*\n"))
print("Optimal b value while trainng= "+str(b_optimal)+str("\n"))
print("***********************************************")

b=0 No of Accurate rows= 285 Accuracy= 62.637362637362635%

b=1 No of Accurate rows= 285 Accuracy= 62.637362637362635%

b=2 No of Accurate rows= 285 Accuracy= 62.637362637362635%

b=3 No of Accurate rows= 285 Accuracy= 62.637362637362635%

b=4 No of Accurate rows= 285 Accuracy= 62.637362637362635%

b=5 No of Accurate rows= 285 Accuracy= 62.637362637362635%

b=6 No of Accurate rows= 285 Accuracy= 62.637362637362635%

b=7 No of Accurate rows= 285 Accuracy= 62.637362637362635%

b=8 No of Accurate rows= 285 Accuracy= 62.637362637362635%

b=9 No of Accurate rows= 285 Accuracy= 62.637362637362635%

b=10 No of Accurate rows= 285 Accuracy= 62.637362637362635%

b=11 No of Accurate rows= 285 Accuracy= 62.637362637362635%

b=12 No of Accurate rows= 286 Accuracy= 62.857142857142854%

b=13 No of Accurate rows= 287 Accuracy= 63.07692307692307%

b=14 No of Accurate rows= 289 Accuracy= 63.51648351648351%

b=15 No of Accurate rows= 293 Accuracy= 64.3956043956044%

b=16 No of Accurate rows= 294 Accuracy

***Testing the model***

In [ ]:
#Testing the model
from random import randint
max_accuracy=0
i=randint(0,X_binarised_test.shape[0])
for b in range (X_binarised_test.shape[1]+1):
    accurate_rows =0

    for x,y in zip(X_binarised_test, Y_test):
        y_pred=(np.sum(x)>=b)
        accurate_rows +=(y == y_pred )
    
    #Calculating the accuracy for every value of b
    # Accuracy = Num of rows predicted correctly/total number of rows
    accuracy=(accurate_rows/X_binarised_test.shape[0])*100

    print("b="+str(b),end=" ")
    print("No of Accurate rows= "+str(accurate_rows),end=" ")
    print("Accuracy= "+str(accuracy)+str("%\n"))
      
    #Finding the optimal value of b
    if(accuracy>max_accuracy):
      max_accuracy=accuracy
      b_optimal=b

print("***********************************************")
print("Maximum Testing Accuracy= "+str(max_accuracy)+str("%\n"))
print("Optimal b value while testing= "+str(b_optimal)+str("\n"))
print("***********************************************")

    



b=0 No of Accurate rows= 72 Accuracy= 63.1578947368421%

b=1 No of Accurate rows= 72 Accuracy= 63.1578947368421%

b=2 No of Accurate rows= 72 Accuracy= 63.1578947368421%

b=3 No of Accurate rows= 72 Accuracy= 63.1578947368421%

b=4 No of Accurate rows= 72 Accuracy= 63.1578947368421%

b=5 No of Accurate rows= 72 Accuracy= 63.1578947368421%

b=6 No of Accurate rows= 72 Accuracy= 63.1578947368421%

b=7 No of Accurate rows= 72 Accuracy= 63.1578947368421%

b=8 No of Accurate rows= 72 Accuracy= 63.1578947368421%

b=9 No of Accurate rows= 72 Accuracy= 63.1578947368421%

b=10 No of Accurate rows= 73 Accuracy= 64.03508771929825%

b=11 No of Accurate rows= 74 Accuracy= 64.91228070175438%

b=12 No of Accurate rows= 74 Accuracy= 64.91228070175438%

b=13 No of Accurate rows= 74 Accuracy= 64.91228070175438%

b=14 No of Accurate rows= 74 Accuracy= 64.91228070175438%

b=15 No of Accurate rows= 77 Accuracy= 67.54385964912281%

b=16 No of Accurate rows= 77 Accuracy= 67.54385964912281%

b=17 No of Accura



---

***Obervations:***

On training the model for different values of b we find the training model has a maximum accuracy if 85.27% for b=28

But while testing, maximum accuracy of 90.35% is obtained for b=24. For b=28 we get a good accuracy of 87.71%



---

